# Generated by Django 5.2.6 on 2025-11-23 00:53

import django.db.models.deletion
import echomusicApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('imagen', models.ImageField(default='/default/img_album.svg', upload_to='', validators=[echomusicApp.models.imagen_valida])),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('autor', models.CharField(max_length=30)),
                ('imagen', models.ImageField(default='/default/img_album.svg', upload_to='', validators=[echomusicApp.models.imagen_valida])),
                ('archivo', models.FileField(unique=True, upload_to='', validators=[echomusicApp.models.audio_valido])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, default='/default/img_perfil.svg', null=True, upload_to='', validators=[echomusicApp.models.imagen_valida])),
            ],
        ),
        migrations.CreateModel(
            name='Album_Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.album')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.cancion')),
            ],
        ),
        migrations.AddField(
            model_name='cancion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.usuario'),
        ),
        migrations.AddField(
            model_name='album',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.usuario'),
        ),
    ]
