# Generated by Django 5.2.7 on 2025-11-17 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen', models.ImageField(blank=True, default='/static/images/icons/img_playlist.svg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, default='/static/images/icons/img_perfil.svg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('autor', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, default='/static/images/icons/img_playlist.svg', null=True, upload_to='')),
                ('archivo', models.FileField(unique=True, upload_to='')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.album')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.usuario'),
        ),
    ]
