# Generated by Django 5.2.7 on 2025-11-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='/static/images/icons/img_perfil.svg', null=True, upload_to=''),
        ),
    ]
