# Generated by Django 5.2.6 on 2025-11-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albumes',
            new_name='Album',
        ),
    ]
