# Generated by Django 4.2 on 2025-11-24 04:43

from django.db import migrations, models
import django.db.models.deletion
import echomusicApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(default='/default/img_album.svg', upload_to='', validators=[echomusicApp.models.imagen_valida])),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.cancion')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.playlist')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('playlist', 'cancion')},
            },
        ),
    ]
