# Generated by Django 5.2.7 on 2025-11-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='/static/images/icons/img_playlist.svg', upload_to=''),
        ),
    ]
