# Generated by Django 5.2.7 on 2025-11-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='album',
        ),
        migrations.CreateModel(
            name='Album_Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.album')),
                ('cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.cancion')),
            ],
        ),
    ]
