# Generated by Django 5.2.7 on 2025-11-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0002_alter_cancion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(blank=True, default='/static/images/icons/img_album.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='/static/images/icons/img_album.svg', upload_to=''),
        ),
    ]
