# Generated by Django 5.2.7 on 2025-11-21 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0002_remove_cancion_album_album_cancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_cancion',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.album'),
        ),
    ]
