# Generated by Django 5.2.6 on 2025-11-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0002_rename_albumes_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(blank=True, default='/static/images/icons/img_playlist.svg', null=True, upload_to=''),
        ),
    ]
