# Generated by Django 5.2.7 on 2025-11-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0003_alter_album_cancion_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_cancion',
            name='cancion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomusicApp.cancion'),
        ),
    ]
