# Generated by Django 5.2.7 on 2025-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0003_alter_album_imagen_alter_cancion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(blank=True, default='/default/img_album.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='/default/img_album.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='/default/img_perfil.svg', null=True, upload_to=''),
        ),
    ]
