# Generated by Django 5.2.7 on 2025-11-20 03:32

import echomusicApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0004_alter_album_imagen_alter_cancion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(blank=True, default='/default/img_album.svg', null=True, upload_to='', validators=[echomusicApp.models.imagen_valida]),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(unique=True, upload_to='', validators=[echomusicApp.models.audio_valido]),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='/default/img_album.svg', upload_to='', validators=[echomusicApp.models.imagen_valida]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='/default/img_perfil.svg', null=True, upload_to='', validators=[echomusicApp.models.imagen_valida]),
        ),
    ]
