# Generated by Django 5.2.7 on 2025-11-20 05:36

import echomusicApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomusicApp', '0005_alter_album_descripcion_alter_album_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(default='/default/img_album.svg', upload_to='', validators=[echomusicApp.models.imagen_valida]),
        ),
    ]
